# Generated by Django 5.2.6 on 2025-09-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0002_estadoturno_horario_producto_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoturno',
            name='nombre',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=50, unique=True),
        ),
    ]