# Generated by Django 5.2.6 on 2025-09-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
