# Generated by Django 5.2.6 on 2025-10-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0005_metodopago_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.ForeignKey(default='pendiente', on_delete=django.db.models.deletion.CASCADE, to='Otros.estadoturno'),
        ),
    ]
