# Generated by Django 5.2.6 on 2025-10-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0007_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estadoturno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviciosxturno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
