# Generated by Django 5.2.6 on 2025-10-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0008_detalleventa_activo_estadoturno_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
    ]
