# Generated by Django 5.2.6 on 2025-10-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0010_empleado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
