# Generated by Django 5.2.6 on 2025-10-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0011_alter_cliente_first_name_alter_cliente_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tranferencia', 'Transferencia'), ('tarjeta débito', 'Tarjeta Débito'), ('tarjeta crédito', 'Tarjeta Crédito'), ('qr', 'QR')], max_length=50),
        ),
    ]
