# Generated by Django 5.2.6 on 2025-11-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0013_detalleventa_servicio_alter_detalleventa_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='estadoturno',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
