# Generated by Django 5.2.6 on 2025-11-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0014_remove_cliente_notas_remove_estadoturno_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
