# Generated by Django 5.2.6 on 2025-11-25 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0015_turno_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Otros.turno'),
        ),
    ]
