# Generated by Django 5.2.6 on 2025-11-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0016_venta_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='turno',
        ),
    ]
