# Generated by Django 5.2.6 on 2025-11-27 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otros', '0017_remove_venta_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Otros.turno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='especialidad',
            field=models.CharField(choices=[('Barbero', 'Barbero'), ('Recepcionista', 'Recepcionista'), ('Gerente', 'Gerente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='estadoturno',
            name='nombre',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tranferencia', 'Transferencia'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Tarjeta Crédito', 'Tarjeta Crédito'), ('QR', 'QR')], max_length=50),
        ),
    ]
